# Generated by Django 6.1.1 on 2026-09-20 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cancelada', 'Cancelada')], default='activa', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('capacidad_maxima', models.PositiveIntegerField()),
                ('ubicacion', models.CharField(blank=True, max_length=120, null=True)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('PROFESOR', 'Docente'), ('ALUMNO', 'Estudiante'), ('JEFE', 'Jefatura / Rector')], default='ALUMNO', max_length=15)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_sesion', models.DateField()),
                ('presente', models.BooleanField(default=False)),
                ('observacion', models.TextField(blank=True, max_length=210, null=True)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='talleres.inscripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=198)),
                ('descripcion', models.TextField(blank=True)),
                ('cupo_maximo', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateTimeField()),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado por Docente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado por jefatura'), ('finalizado', 'Finalizado')], default='solicitado', max_length=22)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='talleres', to='talleres.sala')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='talleres_a_cargo', to='talleres.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='taller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='talleres.taller'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='talleres.usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('alumno', 'taller')},
        ),
    ]
